/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_edma.h"
#include "fsl_dmamux.h"
#include "fsl_common.h"
#include "fsl_uart.h"
#include "fsl_clock.h"
#include "fsl_uart_edma.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA_DMA_BASEADDR DMA0
/* Associated DMAMUX device that is used for muxing of requests. */
#define DMA_DMAMUX_BASEADDR DMAMUX
/* Definition of peripheral ID */
#define UART1_PERIPHERAL UART1
/* Definition of the clock source frequency */
#define UART1_CLOCK_SOURCE CLOCK_GetFreq(UART1_CLK_SRC)
/* UART1 eDMA source request. */
#define UART1_RX_DMA_REQUEST kDmaRequestMux0UART1Rx
/* Selected eDMA channel number. */
#define UART1_RX_DMA_CHANNEL 1
/* DMAMUX device that is used for muxing of the request. */
#define UART1_RX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define UART1_RX_DMA_BASEADDR DMA0
/* UART1 eDMA source request. */
#define UART1_TX_DMA_REQUEST kDmaRequestMux0UART1Tx
/* Selected eDMA channel number. */
#define UART1_TX_DMA_CHANNEL 0
/* DMAMUX device that is used for muxing of the request. */
#define UART1_TX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define UART1_TX_DMA_BASEADDR DMA0
/* Definition of peripheral ID */
#define UART2_PERIPHERAL UART2
/* Definition of the clock source frequency */
#define UART2_CLOCK_SOURCE CLOCK_GetFreq(UART2_CLK_SRC)
/* UART2 eDMA source request. */
#define UART2_RX_DMA_REQUEST kDmaRequestMux0UART2Rx
/* Selected eDMA channel number. */
#define UART2_RX_DMA_CHANNEL 2
/* DMAMUX device that is used for muxing of the request. */
#define UART2_RX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define UART2_RX_DMA_BASEADDR DMA0
/* UART2 eDMA source request. */
#define UART2_TX_DMA_REQUEST kDmaRequestMux0UART2Tx
/* Selected eDMA channel number. */
#define UART2_TX_DMA_CHANNEL 3
/* DMAMUX device that is used for muxing of the request. */
#define UART2_TX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define UART2_TX_DMA_BASEADDR DMA0

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const edma_config_t DMA_config;
extern const uart_config_t UART1_config;
extern edma_handle_t UART1_RX_Handle;
extern edma_handle_t UART1_TX_Handle;
extern uart_edma_handle_t UART1_UART_eDMA_Handle;
extern const uart_config_t UART2_config;
extern edma_handle_t UART2_RX_Handle;
extern edma_handle_t UART2_TX_Handle;
extern uart_edma_handle_t UART2_UART_eDMA_Handle;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
